/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author iain
 */
public class CalendarMonth extends javax.swing.JPanel
{

    // Constructor
    /**
     * Creates new form CalendarMonth
     */
    public CalendarMonth()
    {
        // Setup the list of CalendarDays which will be displayed in the panel
        calendarDays = new ArrayList<>(42);
        for (int iCalendarDay = 0; iCalendarDay < 42; iCalendarDay++)
        {
            calendarDays.add(new CalendarDay());
        }
        // Set the currentMonthStart to this month
        currentMonthStart = new GregorianCalendar();
        currentMonthStart.set(Calendar.DAY_OF_MONTH, 1);
        initComponents();
        refreshCalendarDays();
    }

    // Public Methods
    public void setDate(int year, int month)
    {
        currentMonthStart = new GregorianCalendar(year, month, 1);
        refreshCalendarDays();
    }

    // Private Methods
    private void refreshCalendarDays()
    {
        // Clear the current compoenents from the Panel
        this.removeAll();

        // We'll need to keep track of how many CalendarDays we've added to the
        // panel
        int calendarDaysAdded = 0;

        // First we need to clone the currentMonthStart, as we'll be altering it
        // as we go
        GregorianCalendar calendarDate
                = (GregorianCalendar) currentMonthStart.clone();

        // Then we need to iterate back to the first day of the week
        while (calendarDate.get(Calendar.DAY_OF_WEEK) != calendarDate.getFirstDayOfWeek())
        {
            calendarDate.add(Calendar.DAY_OF_WEEK, -1);
        }

        // Then we need to add each day to the calendarDays list, until we're
        // at the start of the month we want
        while (calendarDate.get(Calendar.MONTH) != currentMonthStart.get(Calendar.MONTH))
        {

            calendarDays.get(calendarDaysAdded).setDate(calendarDate);
            calendarDays.get(calendarDaysAdded).setForeground(Color.LIGHT_GRAY);

            // TODO: Set Schedule for this day
            add(calendarDays.get(calendarDaysAdded));
            calendarDaysAdded += 1;
            calendarDate.add(Calendar.DAY_OF_WEEK, 1);
        }

        // Then we need to add each day to the calendarDays list, until we've
        // reached the end of the last day in this calendar month
        while (calendarDate.get(Calendar.MONTH) == currentMonthStart.get(Calendar.MONTH))
        {
            calendarDays.get(calendarDaysAdded).setDate(calendarDate);
            calendarDays.get(calendarDaysAdded).setForeground(Color.BLACK);

            // TODO: Set Schedule for this day
            add(calendarDays.get(calendarDaysAdded));
            calendarDaysAdded += 1;
            calendarDate.add(Calendar.DAY_OF_WEEK, 1);
        }

        // Then we need to fill up the rest of the list with the remaining days
        // left in this week
        while (calendarDate.get(Calendar.DAY_OF_WEEK) != calendarDate.getFirstDayOfWeek())
        {
            calendarDays.get(calendarDaysAdded).setDate(calendarDate);
            calendarDays.get(calendarDaysAdded).setForeground(Color.LIGHT_GRAY);

            // TODO: Set Schedule for this day
            add(calendarDays.get(calendarDaysAdded));
            calendarDaysAdded += 1;
            calendarDate.add(Calendar.DAY_OF_WEEK, 1);
        }

        // Revalidate and paint the panel
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(0, 7));
    }// </editor-fold>//GEN-END:initComponents

    // Private Member Variables
    private final ArrayList<CalendarDay> calendarDays;
    private GregorianCalendar currentMonthStart;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
