/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import businessobjects.BaseBusinessObject;
import businessobjects.BusinessObjectList;

/**
 * Ui class representing a standard ListView for BusinessObjects with
 * customizable Edit, Add and Delete buttons.
 *
 * @author Iain Workman
 */
public class EditableBusinessObjectListView<T extends BaseBusinessObject>
        extends javax.swing.JPanel {

    /**
     * Creates new form EditableBusinessObjectListView
     * @param data::BusinessObjectList<T> ~ The BusinessObjectList to display
     */
    public EditableBusinessObjectListView(BusinessObjectList<T> data) {
        initComponents();
        businessObjectListView = new BusinessObjectListView<>(data);
        listViewScrollPane.setViewportView(businessObjectListView);
    }

    public void setEditModeEnabled(boolean editEnabled) {
        this.editButton.setVisible(editEnabled);
        updateButtonPanelVisibility();
    }

    public void setAddModeEnabled(boolean addEnabled) {
        this.addButton.setVisible(addEnabled);
        updateButtonPanelVisibility();
    }

    public void setDeleteModeEnabled(boolean deleteEnabled) {
        this.deleteButton.setVisible(deleteEnabled);
        updateButtonPanelVisibility();
    }

    private void updateButtonPanelVisibility() {
        
        boolean showButtonPanel = false;
        showButtonPanel |= editButton.isVisible();
        showButtonPanel |= addButton.isVisible();
        showButtonPanel |= deleteButton.isVisible();
        
        buttonPanel.setVisible(showButtonPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        listPanel = new javax.swing.JPanel();
        listViewScrollPane = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Add.png"))); // NOI18N
        addButton.setToolTipText("Add");
        addButton.setBorder(null);
        buttonPanel.add(addButton);

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Edit.png"))); // NOI18N
        editButton.setBorder(null);
        buttonPanel.add(editButton);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Close.png"))); // NOI18N
        deleteButton.setBorder(null);
        buttonPanel.add(deleteButton);

        add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        listPanel.setLayout(new java.awt.BorderLayout());

        listViewScrollPane.setBorder(null);
        listPanel.add(listViewScrollPane, java.awt.BorderLayout.CENTER);

        add(listPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel listPanel;
    private javax.swing.JScrollPane listViewScrollPane;
    // End of variables declaration//GEN-END:variables
    private final BusinessObjectListView<T> businessObjectListView;
}
