/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import database.JdbcDatabase;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iain
 */
public class MainMenu extends java.awt.Frame {

    /**
     * 
     * @throws SQLException 
     */
    public MainMenu() throws SQLException {
        initComponents();
        // Just testing the database connection right now. Later this will
        // be moved up one level, and the main menu will be passed the database
        // via DI
        JdbcDatabase database = new JdbcDatabase(
                "jdbc:postgresql://edjo.usask.ca/cmpt370_group06",
                "cmpt370_group06",
                "mu5jd8m1ae");
        
        try{
            ResultSet results = database.executeSelect("SELECT * FROM volunteer;");
            ResultSetMetaData metaData = results.getMetaData();
            
            DefaultTableModel currentTableModel = (DefaultTableModel)resultsTable.getModel();
            String[] headers = new String[metaData.getColumnCount()];
            
            
            
            for(int iColumn = 0, columnCount = metaData.getColumnCount();
                    iColumn < columnCount; iColumn++)
            {
                // Seriously!? JDBC indexes its header columns from 1!!
                headers[iColumn] = metaData.getColumnName(iColumn+1);
            }
            
            currentTableModel.setColumnIdentifiers(headers);
            
            resultsTable.setModel(currentTableModel);
        } catch (SQLException ex)
        {
           throw ex; 
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(resultsTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                new MainMenu().setVisible(true);
                } catch (SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, "Could not load main" +
                            " menu.");
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable resultsTable;
    // End of variables declaration//GEN-END:variables
}
